DROP TABLE IF EXISTS `simple_kafka_outbox`;

CREATE TABLE `simple_kafka_outbox` (
    `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `message_id`         VARCHAR(191) NOT NULL COMMENT '消息 ID，全局唯一，消费端幂等键',
    `topic`              MEDIUMTEXT   NOT NULL COMMENT '目标 Kafka topic',
    `record_key`         MEDIUMTEXT COMMENT 'Kafka record key，可为 null',
    `route_key`          MEDIUMTEXT COMMENT 'route 规则匹配 key，可为 null',
    `datasource_key`     MEDIUMTEXT COMMENT '显式 datasource，可为 null',
    `partition`          INT COMMENT '指定分区，可为 null',
    `message_timestamp`  BIGINT COMMENT 'ProducerRecord 时间戳（ms），可为 null',
    `message_type`       MEDIUMTEXT COMMENT '消息类型',
    `payload_kind`       VARCHAR(8)   NOT NULL COMMENT 'payload 类型：STRING/JSON/NULL',
    `payload_json`       MEDIUMTEXT COMMENT 'payload 快照；NULL 类型时为 null',
    `headers_json`       MEDIUMTEXT COMMENT 'headers Map 序列化 JSON，可为 null',
    `attributes_json`    MEDIUMTEXT COMMENT 'attributes Map 序列化 JSON，可为 null',
    `envelope_enabled`   TINYINT(1) COMMENT 'envelope 开关：null=跟随配置，1=开，0=关',
    `trace_id`           MEDIUMTEXT COMMENT '保存时捕获的 traceId，可为 null',
    `schema_version`     TINYINT      NOT NULL DEFAULT 1 COMMENT '快照协议版本，当前固定为 1',
    `status`             VARCHAR(16)  NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING/PROCESSING/RETRY_WAIT/SENT/POISON',
    `attempt`            INT          NOT NULL DEFAULT 0 COMMENT '已尝试投递总次数',
    `available_at`       DATETIME(3)  NOT NULL COMMENT '允许被领取的最早时间',
    `owner_token`        VARCHAR(64) COMMENT '当前持有租约的 worker token',
    `lease_until`        DATETIME(3) COMMENT '租约到期时间',
    `last_error_code`    VARCHAR(64) COMMENT '最近一次失败的错误码',
    `last_error_summary` VARCHAR(512) COMMENT '最近一次失败的脱敏摘要',
    `broker_topic`       MEDIUMTEXT COMMENT 'broker 返回的实际 topic',
    `broker_partition`   INT COMMENT 'broker 返回的分区',
    `broker_offset`      BIGINT COMMENT 'broker 返回的 offset',
    `broker_timestamp`   BIGINT COMMENT 'broker 返回的时间戳（ms）',
    `created_at`         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `sent_at`            DATETIME(3) COMMENT '标记为 SENT 的时间',
    `updated_at`         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    `version`            BIGINT       NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_message_id` (`message_id`),
    KEY `idx_status_available_at_id` (`status`, `available_at`, `id`) COMMENT 'worker 扫描待发送或重试记录',
    KEY `idx_status_lease_until_id` (`status`, `lease_until`, `id`) COMMENT 'worker 扫描租约到期记录',
    KEY `idx_sent_at_id` (`sent_at`, `id`) COMMENT '清理游标'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Kafka outbox 消息记录';
