dependencies {
    api 'io.github.sure-zzzzzz:simple-xff-capture-audit-core:1.0.0'

    testImplementation 'io.github.sure-zzzzzz:simple-xff-capture-starter:1.0.0'

    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly 'org.springframework:spring-context'

    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-log4j2'
}
