dependencies {
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly 'org.springframework.boot:spring-boot-starter-jdbc'
    compileOnly 'org.springframework:spring-tx'

    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    testRuntimeOnly 'com.mysql:mysql-connector-j'
}
